/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import javax.swing.JOptionPane;
/**
 *
 * @author RC_Student_lab
 */
public class Task extends javax.swing.JFrame {

    /**
     * Creates new form Task
     */
    public Task() {
        initComponents();
    }
UserInfo taskinput = new UserInfo();
    
    public boolean checkTaskDescription(){
        if(taskinput.getDiscription().length()<=50){
            return true;
        }
        else {
            return false;
        }
    }
    // this is were i created the task id to display info we getting from the user as is requested by the question
    public static String createTaskID(){
        String count = " ";
        char charecter;
        for(int x = 0; x < UserInfo.getDeveloperNames().length(); x++){
            charecter = UserInfo.getDeveloperNames().charAt(x);
            if(charecter == ' '){
            count = UserInfo.getDeveloperNames().substring(x-3, x);
        }
        }
        String iD = UserInfo.getTaskName().substring(0, 2)+":"+ UserInfo.getTaskNumber()+":"+count;
                
        return iD.toUpperCase();
      
    }
    
    public static String printTaskDetails(){
        return UserInfo.getStatus()+"\n"+UserInfo.getDeveloperNames()+"\n"+UserInfo.getTaskNumber()+"\n"+
                UserInfo.getTaskName()+"\n"+UserInfo.getDiscription()+"\n"+ createTaskID()+"\n"+UserInfo.getDuration();
    }
    
   public int returnTotalHours(){
       return UserInfo.duration;
    }

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class UserInfo {

        private static int duration;

        private static String getTaskName() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String getDiscription() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String getStatus() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static Object getDeveloperNames() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String getTaskNumber() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static String getDuration() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public UserInfo() {
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
